#
# Blockchain node configuration file.
#
# If any of the configuration parameters is not explicitly specified then the
# built-in default value is used.
#

# Logger verbosity level.
# Available options: off, error, warn, info, debug, trace.
# Default: info
log-level = "debug"

# Node keypair file.
# Default: dynamically generated
#keypair-path = "ed25519_keypair.bin"

# Node bootstrap file in WASM format.
# Default: "bootstrap.bin"
bootstrap-path = "./data/bootstrap.bin"

# Http service address.
# Default: 127.0.0.1
rest-addr = "127.0.0.1"

# Http service port.
# Default: 8000
rest-port = 8000

# Bridge service address.
# Default: 127.0.0.1
bridge-addr = "127.0.0.1"

# Bridge service port.
# Default: 8001
bridge-port = 8001

# P2P bootstrap address
# Default: empty
# uncomment the follow to sync with trinci testnet
#p2p-bootstrap-addr = "12D3KooWEAxyiTiBgx8MUtTPUu29VLasimzscC84jTVRtMb5JjGZ@/ip4/15.161.71.249/tcp/9006"

# P2P service address.
# Default: 127.0.0.1
# use 0.0.0.0
p2p-addr = "0.0.0.0"

# P2P service port.
# Default: 0 (random)
p2p-port = 9000

# Database path within the file system.
# Default: "db"
db-path = "db"

# Wasm machine max number of cached contracts.
# Default: 10 (totally arbitrary value)
wm-cache-max = 10

# Offline mode- prevent kad from start
# Default: false
#offline = true

## Indexer configuration

# couchdb Host
# Default: "localhost"
indexer-host = "localhost"

# couchdb Port
# Default: 5984
indexer-port = 5984

# couchdb user
# Default: admin
indexer-username = "admin"

# couchdb password
# Default: password
indexer-password = "password"
